# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adless < Formula
  desc "Local domains blocker written in Go"
  homepage "https://github.com/WIttyJudge/homebrew-adless"
  version "1.0.3"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/WIttyJudge/adless/releases/download/v1.0.3/adless_v1.0.3_darwin_x86_64.tar.gz"
      sha256 "6c11ff290d3b3bb817676b0e00c4f135b9283545ad3939f4b2be8745c6708a41"

      def install
        bin.install "adless"
      end
    end
    on_arm do
      url "https://github.com/WIttyJudge/adless/releases/download/v1.0.3/adless_v1.0.3_darwin_arm64.tar.gz"
      sha256 "b1bb18545e1f0a45804990516160a18a1585b0dba3da779f3ccd4e5c12ad2e09"

      def install
        bin.install "adless"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/WIttyJudge/adless/releases/download/v1.0.3/adless_v1.0.3_linux_x86_64.tar.gz"
        sha256 "4f0238de7281add960e2614f1b794df37f0ab360072759254b0392a256b10b61"

        def install
          bin.install "adless"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/WIttyJudge/adless/releases/download/v1.0.3/adless_v1.0.3_linux_arm64.tar.gz"
        sha256 "ce25047794556248fd07f6b4afe4cd3da09c5c92574adbbd96dbde50451979c5"

        def install
          bin.install "adless"
        end
      end
    end
  end
end
